spring.application.name=trade-surveillance

spring.datasource.url=jdbc:postgresql://localhost:5432/trade_surveillance
spring.datasource.username=postgres
spring.datasource.password=Elina0619!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080